# Generated by Django 3.2.4 on 2021-06-18 12:42

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('rep_name', models.TextField()),
                ('rep_email', models.TextField()),
                ('rep_job_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantTeamMember',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('sex', models.TextField(choices=[('male', 'آقا'), ('female', 'خانم')])),
                ('overconfidence_question_1_min', models.IntegerField()),
                ('overconfidence_question_1_max', models.IntegerField()),
                ('overconfidence_question_2_min', models.IntegerField()),
                ('overconfidence_question_2_max', models.IntegerField()),
                ('overconfidence_question_3_min', models.IntegerField()),
                ('overconfidence_question_3_max', models.IntegerField()),
                ('overconfidence_question_4_min', models.IntegerField()),
                ('overconfidence_question_4_max', models.IntegerField()),
                ('overconfidence_question_5_min', models.IntegerField()),
                ('overconfidence_question_5_max', models.IntegerField()),
                ('overconfidence_question_6_min', models.IntegerField()),
                ('overconfidence_question_6_max', models.IntegerField()),
                ('overconfidence_question_7_min', models.IntegerField()),
                ('overconfidence_question_7_max', models.IntegerField()),
                ('overconfidence_question_8_min', models.IntegerField()),
                ('overconfidence_question_8_max', models.IntegerField()),
                ('overconfidence_question_9_min', models.IntegerField()),
                ('overconfidence_question_9_max', models.IntegerField()),
                ('overconfidence_question_10_min', models.IntegerField()),
                ('overconfidence_question_10_max', models.IntegerField()),
                ('team_coordination_question_1', models.IntegerField()),
                ('team_coordination_question_2', models.IntegerField()),
                ('team_coordination_question_3', models.IntegerField()),
                ('team_coordination_question_4', models.IntegerField()),
                ('team_coordination_question_5', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberVoiceEvaluationByParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_question_1', models.IntegerField()),
                ('voice_question_2', models.IntegerField()),
                ('voice_question_3', models.IntegerField()),
                ('voice_question_4', models.IntegerField()),
                ('voice_question_5', models.IntegerField()),
                ('voice_question_6', models.IntegerField()),
                ('evaluated_participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluated_participant', to='main.participantteammember')),
                ('evaluating_participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluating_participant', to='main.participantteammember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.team')),
            ],
        ),
        migrations.AddField(
            model_name='participantteammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.team'),
        ),
    ]
