# Generated by Django 3.2.4 on 2021-06-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rep_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rep_job_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rep_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='sex',
            field=models.CharField(choices=[('male', 'آقا'), ('female', 'خانم')], max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
