# Generated by Django 3.2.4 on 2021-06-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210618_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Organization's Name"),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_10_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_10_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_1_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_1_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_2_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_2_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_3_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_3_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_4_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_4_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_5_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_5_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_6_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_6_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_7_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_7_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_8_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_8_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_9_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='overconfidence_question_9_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'آقا'), ('female', 'خانم')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='team_coordination_question_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='team_coordination_question_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='team_coordination_question_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='team_coordination_question_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='team_coordination_question_5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
