# Generated by Django 3.2.4 on 2021-06-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210618_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantteammember',
            name='age',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_10_max',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_10_min',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_1_max',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_1_min',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_2_max',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_2_min',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_3_max',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_3_min',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_4_max',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_4_min',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_5_max',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_5_min',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_6_max',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_6_min',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_7_max',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_7_min',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_8_max',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_8_min',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_9_max',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='overconfidence_question_9_min',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='team_coordination_question_1',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='team_coordination_question_2',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='team_coordination_question_3',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='team_coordination_question_4',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='team_coordination_question_5',
        ),
        migrations.AlterField(
            model_name='participantteammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='main.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='main.organization'),
        ),
        migrations.AlterField(
            model_name='teammembervoiceevaluationbyparticipant',
            name='evaluated_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='voice_evaluations_about_participant', to='main.participantteammember'),
        ),
        migrations.AlterField(
            model_name='teammembervoiceevaluationbyparticipant',
            name='evaluating_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='voice_evaluations_by_participant', to='main.participantteammember'),
        ),
        migrations.CreateModel(
            name='TeamCoordinationSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_coordination_question_1', models.IntegerField(blank=True, null=True)),
                ('team_coordination_question_2', models.IntegerField(blank=True, null=True)),
                ('team_coordination_question_3', models.IntegerField(blank=True, null=True)),
                ('team_coordination_question_4', models.IntegerField(blank=True, null=True)),
                ('team_coordination_question_5', models.IntegerField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_coordination_survey_responses', to='main.participantteammember')),
            ],
        ),
        migrations.CreateModel(
            name='OverconfidenceSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overconfidence_question_1_min', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_1_max', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_2_min', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_2_max', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_3_min', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_3_max', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_4_min', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_4_max', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_5_min', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_5_max', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_6_min', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_6_max', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_7_min', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_7_max', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_8_min', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_8_max', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_9_min', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_9_max', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_10_min', models.IntegerField(blank=True, null=True)),
                ('overconfidence_question_10_max', models.IntegerField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overconfidence_survey_responses', to='main.participantteammember')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'آقا'), ('female', 'خانم')], max_length=10, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_survey_responses', to='main.participantteammember')),
            ],
        ),
    ]
