# Generated by Django 3.2.4 on 2021-07-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_organization_rep_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantteammember',
            name='has_participated',
            field=models.BooleanField(default=False),
        ),
    ]
