# Generated by Django 3.2.4 on 2021-07-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_participantteammember_has_participated'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsurveyresponse',
            name='team_history',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalsurveyresponse',
            name='tenure',
            field=models.FloatField(default=0.0),
        ),
    ]
