# Generated by Django 3.2.9 on 2021-11-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211107_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEffectivenessSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.IntegerField(blank=True, null=True)),
                ('question_2', models.IntegerField(blank=True, null=True)),
                ('question_3', models.IntegerField(blank=True, null=True)),
                ('question_4', models.IntegerField(blank=True, null=True)),
                ('question_5', models.IntegerField(blank=True, null=True)),
                ('question_6', models.IntegerField(blank=True, null=True)),
                ('question_7', models.IntegerField(blank=True, null=True)),
                ('question_8', models.IntegerField(blank=True, null=True)),
                ('question_9', models.IntegerField(blank=True, null=True)),
                ('question_10', models.IntegerField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_effectiveness_survey_response', to='main.participantteammember')),
            ],
        ),
    ]
