# Generated by Django 3.2.9 on 2021-12-28 22:15

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', 'آقا'), ('female', 'خانم')], max_length=6)),
                ('tenure', models.FloatField(default=0.0)),
                ('team_history', models.IntegerField(default=0)),
                ('overconfidence_question_one_lower', models.IntegerField()),
                ('overconfidence_question_one_upper', models.IntegerField()),
                ('overconfidence_question_two_lower', models.IntegerField()),
                ('overconfidence_question_two_upper', models.IntegerField()),
                ('overconfidence_question_three_lower', models.IntegerField()),
                ('overconfidence_question_three_upper', models.IntegerField()),
                ('overconfidence_question_four_lower', models.IntegerField()),
                ('overconfidence_question_four_upper', models.IntegerField()),
                ('overconfidence_question_five_lower', models.IntegerField()),
                ('overconfidence_question_five_upper', models.IntegerField()),
                ('overconfidence_question_six_lower', models.IntegerField()),
                ('overconfidence_question_six_upper', models.IntegerField()),
                ('overconfidence_question_seven_lower', models.IntegerField()),
                ('overconfidence_question_seven_upper', models.IntegerField()),
                ('overconfidence_question_eight_lower', models.IntegerField()),
                ('overconfidence_question_eight_upper', models.IntegerField()),
                ('overconfidence_question_nine_lower', models.IntegerField()),
                ('overconfidence_question_nine_upper', models.IntegerField()),
                ('overconfidence_question_ten_lower', models.IntegerField()),
                ('overconfidence_question_ten_upper', models.IntegerField()),
                ('team_coordination_question_one', models.IntegerField()),
                ('team_coordination_question_two', models.IntegerField()),
                ('team_coordination_question_three', models.IntegerField()),
                ('team_coordination_question_four', models.IntegerField()),
                ('team_coordination_question_five', models.IntegerField()),
                ('team_effectiveness_question_one', models.IntegerField()),
                ('team_effectiveness_question_two', models.IntegerField()),
                ('team_effectiveness_question_three', models.IntegerField()),
                ('team_effectiveness_question_four', models.IntegerField()),
                ('team_effectiveness_question_five', models.IntegerField()),
                ('team_effectiveness_question_six', models.IntegerField()),
                ('team_effectiveness_question_seven', models.IntegerField()),
                ('team_effectiveness_question_eight', models.IntegerField()),
                ('team_effectiveness_question_nine', models.IntegerField()),
                ('team_effectiveness_question_ten', models.IntegerField()),
                ('voice_question_one', models.IntegerField()),
                ('voice_question_two', models.IntegerField()),
                ('voice_question_three', models.IntegerField()),
                ('voice_question_four', models.IntegerField()),
                ('voice_question_five', models.IntegerField()),
                ('voice_question_six', models.IntegerField()),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='generalsurveyresponse',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='overconfidencesurveyresponse',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='participantteammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamcoordinationsurveyresponse',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='teameffectivenesssurveyresponse',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='teammembervoiceevaluationbyparticipant',
            name='evaluated_participant',
        ),
        migrations.RemoveField(
            model_name='teammembervoiceevaluationbyparticipant',
            name='evaluating_participant',
        ),
        migrations.RemoveField(
            model_name='teammembervoiceevaluationbyparticipant',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='size',
            field=models.IntegerField(default=3),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='GeneralSurveyResponse',
        ),
        migrations.DeleteModel(
            name='OverconfidenceSurveyResponse',
        ),
        migrations.DeleteModel(
            name='ParticipantTeamMember',
        ),
        migrations.DeleteModel(
            name='TeamCoordinationSurveyResponse',
        ),
        migrations.DeleteModel(
            name='TeamEffectivenessSurveyResponse',
        ),
        migrations.DeleteModel(
            name='TeamMemberVoiceEvaluationByParticipant',
        ),
        migrations.AddField(
            model_name='response',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responses', to='main.team'),
        ),
    ]
