# Generated by Django 3.2.9 on 2021-12-28 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211229_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.team'),
        ),
    ]
