# Generated by Django 3.2.9 on 2022-02-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_team_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='overconfidence_question_one_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True),
        ),
    ]
