# Generated by Django 3.2.9 on 2022-02-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_response_overconfidence_question_one_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='overconfidence_question_eight_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='overconfidence_question_five_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='overconfidence_question_four_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='overconfidence_question_nine_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='overconfidence_question_seven_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='overconfidence_question_six_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='overconfidence_question_ten_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='overconfidence_question_three_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='overconfidence_question_two_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True),
        ),
    ]
