# Generated by Django 3.2.9 on 2022-02-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220202_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverconfidenceQuiz',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.response',),
        ),
    ]
