# Generated by Django 3.2.9 on 2022-03-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_overconfidencequiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overconfidencequiz',
            options={'verbose_name': 'Overconfidence Quiz', 'verbose_name_plural': 'Overconfidence Quizzes'},
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_eight_lower',
            field=models.IntegerField(verbose_name='انسان بالغ به طور میانگین چند دندان دارد؟(L)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_eight_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True, verbose_name='Outcome (32)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_eight_upper',
            field=models.IntegerField(verbose_name='انسان بالغ به طور میانگین چند دندان دارد؟(H)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_five_lower',
            field=models.IntegerField(verbose_name='چند کشور در آمریکای شمالی وجود دارد؟(L)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_five_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True, verbose_name='Outcome (23)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_five_upper',
            field=models.IntegerField(verbose_name='چند کشور در آمریکای شمالی وجود دارد؟(H)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_four_lower',
            field=models.IntegerField(verbose_name='ویندوز ایکس پی در چه سالی عرضه شد؟(L)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_four_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True, verbose_name='Outcome (2000 | 1380)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_four_upper',
            field=models.IntegerField(verbose_name='ویندوز ایکس پی در چه سالی عرضه شد؟(H)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_nine_lower',
            field=models.IntegerField(verbose_name='مسافت تهران تا مشهد چند کیلومتر است؟(L)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_nine_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True, verbose_name='Outcome (899~926)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_nine_upper',
            field=models.IntegerField(verbose_name='مسافت تهران تا مشهد چند کیلومتر است؟(H)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_one_lower',
            field=models.IntegerField(verbose_name='کشور ایران در حال حاضر (سال ۱۴۰۰) چند استان دارد؟(L)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_one_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True, verbose_name='Outcome (31)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_one_upper',
            field=models.IntegerField(verbose_name='کشور ایران در حال حاضر (سال ۱۴۰۰) چند استان دارد؟(H)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_seven_lower',
            field=models.IntegerField(verbose_name='اولین موتور جستجوی وب در چه سالی ساخته شد؟(L)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_seven_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True, verbose_name='Outcome (1993~1998 | 1371~1377)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_seven_upper',
            field=models.IntegerField(verbose_name='اولین موتور جستجوی وب در چه سالی ساخته شد؟(H)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_six_lower',
            field=models.IntegerField(verbose_name='وب جهانی  در چه سالی اختراع شد؟(L)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_six_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True, verbose_name='Outcome (1989 | 1368)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_six_upper',
            field=models.IntegerField(verbose_name='وب جهانی  در چه سالی اختراع شد؟(H)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_ten_lower',
            field=models.IntegerField(verbose_name='قدمت (سن) برج آزادی تهران چند سال است؟(L)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_ten_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True, verbose_name='Outcome (50)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_ten_upper',
            field=models.IntegerField(verbose_name='قدمت (سن) برج آزادی تهران چند سال است؟(H)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_three_lower',
            field=models.IntegerField(verbose_name='در اروپا چند کشور وجود دارد (که سازمان ملل به رسمیت می\u200cشناسد)؟(L)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_three_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True, verbose_name='Outcome (44)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_three_upper',
            field=models.IntegerField(verbose_name='در اروپا چند کشور وجود دارد (که سازمان ملل به رسمیت می\u200cشناسد)؟(H)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_two_lower',
            field=models.IntegerField(verbose_name='در چه سالی تلفن همراه اپل با نام آیفون برای اولین بار عرضه شد؟(L)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_two_outcome',
            field=models.IntegerField(blank=True, choices=[(-1, 'Too Broad: Underconfident'), (0, 'OK'), (1, 'Miss: Overconfident')], null=True, verbose_name='Outcome (2007 | 1386-7)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='overconfidence_question_two_upper',
            field=models.IntegerField(verbose_name='در چه سالی تلفن همراه اپل با نام آیفون برای اولین بار عرضه شد؟(H)'),
        ),
    ]
